const tocRoot = document.getElementById("toc");
const sections = Array.from(document.querySelectorAll("[data-toc]"));
const modal = document.getElementById("video-modal");
const modalTitle = document.getElementById("video-modal-title");
const modalPlayer = document.getElementById("video-modal-player");
const videoCarousels = Array.from(document.querySelectorAll("[data-video-carousel]"));
const langButtons = Array.from(document.querySelectorAll(".js-lang-toggle"));

const englishCopy = {
  "hero-lead": "Data is essential to embodied intelligence, but how should we scale it, and which data deserves to be scaled? With Psi-R2.5, continued cleaning and refinement of human data has helped us identify the data and properties that matter most, and has changed how we think about model training. Here is our recent progress from the perspective of data.",
  read: "Start reading",
  watch: "Watch demo",
  play: "Play",
  "diagram-caption": "The two-level Psi-R2.5 architecture: the high-level planner (Vision Language Model) sends Subtext and Value to the low-level controller (World Action Model), which interacts with the environment through Action and learns from Feedback.",
  "multitask-caption": "Psi-R2.5 multi-task evaluation",
  "icl-caption": "Psi-R2.5 In-Context Learning demonstrations · Select a thumbnail to switch videos",
  "icl-current-label": "Now showing",
  "postrl-caption": "Generalization across 3C-box assembly, long-horizon tasks, and dexterous manipulation · Click any video to enlarge",
  "weak-pair-title": "Weak Pair Data",
  "strong-pair-title": "Strong Pair Data",
  "weak-pair-description": "Paired by task semantics",
  "strong-pair-description": "Aligned scenes and frame-by-frame correspondence",
  "pair-human": "Human data",
  "pair-robot": "Robot data",
  "pair-comparison-caption": "Weak and strong pair data · Click either video to enlarge",
  "multi-pair-caption": "High-quality robot–human paired videos · Click any video to enlarge",
  r25: {
    paragraphs: [
      "Our latest model, Psi-R2.5, uses a two-level architecture. The upper level acts as the brain: it breaks a long instruction into subtasks and sends each subtask, together with the current observation, to the lower-level model, which produces the robot's action trajectory. The upper-level backbone is QwenVL3.5-4B and the lower-level backbone is Wan2.2-IT2V-5B. Both are trained on the same pretraining data.",
      "Compared with R2, the central changes in R2.5 concern data quality and the compression of data properties. After reaching 100,000 hours, we conducted a thorough review of the entire dataset instead of simply collecting more hours. We compressed redundant information, scaled up strong pair data to improve the conversion of human data into robot data, and refined both qualitative and quantitative assessments of data quality.",
      "We also introduced simulation-based evaluation during training of both levels of the model. A small set of simulation tasks is included in pretraining, and we evaluate the model directly in simulation. To measure the capabilities of the base model on hardware, we built a real-robot benchmark of 50 complex tasks and continually randomize each task's initial state. We hope this will provide a useful test of compositional generalization.",
      "For embodied pretraining, architecture is usually the least consequential choice: it can be changed in a matter of days. Data is what determines performance. Embodied data can be extraordinarily noisy. Feeding everything into one model is almost like first training a classifier to distinguish human from robot data and then letting it choose different parameters for each. The real challenge is getting the model to understand human data as robot data.",
      "R2.5 addresses this in two ways: we align human and robot data using strong pair data, and we require more precise language annotations. In other work, corresponding human and robot examples, such as both picking up the same bottle, are labeled and trained together in the hope that the model learns their relationship. We call such examples pair data.",
      "In R2 and W0, released in April, we used reinforcement learning in a world model to explicitly convert human data into corresponding robot data. This produces robot trajectories with actions that can be successfully replayed, but the pipeline is complex. We call a pair strong when its images are nearly identical apart from the embodiment, its frames correspond in time, and its actions can be replayed on a robot. Examples collected merely for the same semantic task are weak pairs. A strong pair effectively places the dynamics of human data in the same domain as robot dynamics, and can be scaled.",
      "To produce strong pairs more efficiently, we used the high-quality pairs generated by R2 and W0 to train an end-to-end conversion model that directly maps human data to robot data. In the past, high-quality strong pairs were extremely difficult to collect, leaving mostly weak pairs that could not provide this degree of alignment. We discuss the implementation later in the article.",
      "Another crucial property is the precision of language annotation. Our Autolabeling pipeline annotates every decomposed atomic task at the finest practical level. We also place strong demands on task diversity: we keep the amount of data per task small and use our data operations process to cover a wider range of tasks.",
      "Hours alone say little about information content. For example, 10,000 hours across 100 tasks with 100 hours per task might convey no more information than 100 hours across the same 100 tasks with one hour per task. We therefore reduce redundancy within a given number of hours, collect as many different tasks as possible, and carefully annotate and review each atomic action.",
      "Embodied intelligence cannot stop at pretraining. What sets it apart from traditional custom automation is the prospect of reducing deployment costs; that is the commercial value of a base model. We train a base model to reduce the data needed for few-shot post-training. Yet zero-shot deployment at a customer site remains unlikely in the near term: the required SKUs and cycle times are too specific. Post-training will remain necessary for some time.",
      "We developed a dexterous-hand HIL and RL post-training framework. With very little data, it fine-tunes the base model for complex tasks while collecting failures during deployment and feeding them back into training. Phone-box assembly, for instance, has many precise steps and achieves a low success rate when learned from scratch by imitation. After several HIL and RL iterations, we reached 99% success in only one or two working days. The same approach is deployed at customer sites to handle difficult corner cases."
    ],
    placeholders: []
  },
  "pair-data": {
    paragraphs: [
      "Human data has recently become a major subject of research. The central question is how to bring its quality up to that of real robot data and align the two. Historically, human data has mainly been used for pretraining, followed by post-training on real-robot data to complete a task.",
      "Simply pouring human data into a model is crude. In a fixed evaluation setting, adding low-quality data after training on high-quality examples can actually hurt performance: the extra noise outweighs the information it contributes. This is why it is hard to demonstrate the value of human-data pretraining; human data has a much lower signal-to-noise ratio than real-robot data. If a batch of human demonstrations cannot train a model to perform that task, why expect it to help the larger model learn the task?",
      "As a result, most human-data pretraining provides only high-level guidance and contributes little to physical manipulation, even though manipulation is the modality embodied intelligence most needs to scale. This resembles the rationale for zero-shot Sim2Real: researchers often use zero-shot rather than few-shot transfer to test whether the simulation is useful. If a model trained solely in simulation performs poorly, the data or simulation parameters are probably wrong.",
      "The same standard should apply to human data. The most valuable human data is data that can train an effective model directly, and that is the data we want for pretraining. We therefore built a quality-analysis method with two tests: replay the converted trajectory on a robot to see whether it completes the task, and use the converted data for post-training to see whether the resulting model generalizes. Our converter, trained on strong pair data, aligns human and robot data and performs well on both tests.",
      "We first review existing ways of post-training with human data, then explain how strong pair data makes it possible in our approach.",
      "A small but growing body of research studies training solely on human data. Like the sim-to-real gap, the embodiment gap has two components:",
      "Most human-only training methods attempt to resolve these two gaps. One approach reconstructs human data in a simulator using real2sim, trains a model through trajectory optimization or reinforcement learning, and then transfers it with sim2real. This extends earlier Sim2Real work, but real2sim itself is difficult to scale and the sim-to-real gap remains.",
      "Another approach uses simulation to process data instead of training a policy in the simulator. For the visual gap, it segments out the hand, applies inpainting, and overlays a rendered robot. For the dynamics gap, it applies trajectory optimization or reinforcement learning to produce better training data for a policy.",
      "Unlike the first approach, the second uses simulation for data processing and then trains a visuomotor policy through imitation learning. But it still faces two problems: real2sim does not scale easily, and inpainting cannot reliably reconstruct complex relationships such as occlusion. Some methods can replace a human hand with a robot hand, but current depth estimates cannot resolve whether fingers are in front of or behind an object; the result may show the hand passing through it. These interactions are precisely the information the model needs most.",
      "For a long time, these limitations confined the field to simple, highly customized tasks and led many to doubt that human data alone could train models for complex manipulation. Our team has explored this direction from early on and tried nearly every available method. We eventually replaced the simulator with Psi-W0, a world model pretrained on roughly 100,000 hours of human data. With reinforcement learning in the world model, we can optimize a human-hand trajectory into an executable robot trajectory and convert human data into robot data.",
      "This follows the earlier logic, but replacing a conventional simulator with a world model avoids much of the sim-to-real gap and the difficulty of scaling real2sim. The pipeline is still heavy: the policy and world model must roll out together, followed by RL fine-tuning. We collect the strong pairs converted by Psi-W0 and distill this entire process into a direct human-to-robot data converter.",
      "Even that is slow. We realized that these methods are difficult because they have to invent robot data to match an existing human demonstration, using RL or trajectory optimization to close the embodiment gap. What if we start instead with real robot data and create the corresponding human data? The robot visuals and dynamics are already usable as they are.",
      "With enough human demonstrations paired to real-robot data, we can train a model that takes human-hand data and predicts matching robot images and actions. Reversing Psi-W0 lets us start from actual robot data and generate the corresponding human-hand data, producing high-quality pairs directly.",
      "These pairs let us train an end-to-end, action-aware model to align human data directly with robot data. We validate its output with the two tests above: the converted data can be replayed on a robot and used to train a model. Even for especially complex tasks that are not completed perfectly, the trajectories of both hands are generally close to the desired motion.",
      "The converter is not a policy; it is an action-aware video-editing model. Because the robot's action space is finite, zero-shot generalization is more achievable. A person can record a human manipulation with an ordinary phone or camera and use our pipeline to turn it into data for different robots."
    ],
    gaps: [
      "Whether the human is bare-handed or wearing gloves, the visual input can differ greatly from the robot's observations. The gap extends beyond the pixels of the hands and robot to camera parameters and changes in the environment.",
      "Human actions are obtained from devices or visual estimates rather than recorded directly from a robot. Three sources of error follow: sensor or vision errors in hand-pose estimation, kinematic differences between human and robot joints, and differences in physical properties such as friction."
    ],
    placeholders: [
      "Live recording and conversion into robot-operation data video to be added"
    ]
  },
  icl: {
    paragraphs: [
      "In-Context Learning and Test-Time Training seek to let a person demonstrate a task once, then use that trajectory as a prompt to guide a robot through a task it could not previously complete, without retraining or fine-tuning.",
      "The intuition is that training a robot to do any task anywhere is hard, while training it to complete a task after seeing one demonstration is more tractable. Unlike language models, a robot's context is not another robot demonstration but a human demonstration.",
      "However, our strong pair data model lets us readily convert human data into corresponding robot data and provide a better prompt to the model. This makes efficient In-Context Learning possible, as the video below illustrates. In-context learning (ICL) enables a robot to zero-shot generalize to new tasks from context, without updating its model parameters. Instead of retraining for every new task, the robot can infer what to do and how to do it from text prompts or physical prompts. We will share more details later."
    ],
    placeholders: []
  },
  closing: {
    paragraphs: [
      "If you are interested in collaborating, please reach out. We are especially interested in working with companies that are continuing to scale up their data collection.",
      "We are also hiring. If you would like to join us, we would love to hear from you.",
      "If you are interested in our work, potential collaborations, or any other questions, please write to market@psirobot.ai."
    ],
    placeholders: []
  }
};

const translatedElements = [];

document.querySelectorAll("[data-i18n]").forEach((element) => {
  translatedElements.push({ element, zh: element.textContent.trim(), en: englishCopy[element.dataset.i18n] });
});

for (const sectionId of ["r25", "pair-data", "icl", "closing"]) {
  const section = document.getElementById(sectionId);
  const copy = englishCopy[sectionId];
  const paragraphs = section.querySelectorAll(".section-copy > p:not(.kicker)");
  const gaps = section.querySelectorAll(".gap-list span");
  const placeholders = section.querySelectorAll(".media-placeholder > span:last-child");

  for (const [elements, translations] of [
    [paragraphs, copy.paragraphs],
    [gaps, copy.gaps || []],
    [placeholders, copy.placeholders]
  ]) {
    if (elements.length !== translations.length) {
      throw new Error(`Translation count mismatch in ${sectionId}`);
    }
    elements.forEach((element, index) => {
      translatedElements.push({ element, zh: element.textContent.trim(), en: translations[index] });
    });
  }
}

const placeholderLabels = { "效果占位": "Demo pending", "展示占位": "Media pending", "对比占位": "Comparison pending", "视频占位": "Video pending" };
document.querySelectorAll(".media-placeholder-label").forEach((element) => {
  translatedElements.push({ element, zh: element.textContent.trim(), en: placeholderLabels[element.textContent.trim()] });
});

let activeCarousel = null;

function buildToc() {
  if (!tocRoot) return;

  sections.forEach((section) => {
    const id = section.id;
    const label = section.dataset.toc;
    if (!id || !label) return;

    const link = document.createElement("a");
    link.href = `#${id}`;
    link.textContent = label;
    tocRoot.appendChild(link);
  });
}

function updateActiveToc() {
  if (!tocRoot) return;

  const links = Array.from(tocRoot.querySelectorAll("a"));
  if (!links.length) return;

  let currentId = sections[0]?.id;
  const threshold = window.innerHeight * 0.24;

  sections.forEach((section) => {
    const rect = section.getBoundingClientRect();
    if (rect.top <= threshold) {
      currentId = section.id;
    }
  });

  links.forEach((link) => {
    link.classList.toggle("is-active", link.getAttribute("href") === `#${currentId}`);
  });
}

let activeVideoTrigger = null;
let pausedGalleryVideos = [];
let iclShowcase = null;

function openVideo(src, title, trigger) {
  if (!src || !modal || !modalPlayer) return;

  activeVideoTrigger = trigger || document.activeElement;
  pausedGalleryVideos = Array.from(document.querySelectorAll(".postrl-gallery video, .pair-comparison video, .multi-pair-gallery video, #icl-player"))
    .filter((video) => !video.paused);
  modal.classList.add("is-open");
  iclShowcase?.refreshPlayback();
  pausedGalleryVideos.forEach((video) => video.pause());
  modal.setAttribute("aria-hidden", "false");
  document.body.style.overflow = "hidden";
  modalTitle.textContent = title || "Demo Video";
  const preview = trigger?.querySelector("video");
  const aspect = preview?.videoWidth && preview.videoHeight
    ? preview.videoWidth / preview.videoHeight
    : 16 / 9;
  modal.style.setProperty("--video-aspect", aspect);
  modalPlayer.loop = Boolean(trigger?.querySelector("video[loop]"));
  modalPlayer.muted = modalPlayer.loop;
  modalPlayer.src = src;
  modalPlayer.play().catch(() => {});
  document.querySelector(".page-shell").inert = true;
  modal.querySelector(".video-modal-close").focus();
}

function closeVideo() {
  if (!modal || !modalPlayer) return;

  modal.classList.remove("is-open");
  modal.setAttribute("aria-hidden", "true");
  document.body.style.overflow = "";
  modalPlayer.pause();
  modalPlayer.removeAttribute("src");
  modalPlayer.load();
  document.querySelector(".page-shell").inert = false;
  activeVideoTrigger?.focus({ preventScroll: true });
  activeVideoTrigger = null;
  pausedGalleryVideos.forEach((video) => {
    if (video !== iclShowcase?.player) video.play().catch(() => {});
  });
  iclShowcase?.refreshPlayback();
  pausedGalleryVideos = [];
}

function wireVideos() {
  const openButtons = Array.from(document.querySelectorAll(".js-open-video"));

  modalPlayer.addEventListener("loadedmetadata", () => {
    if (modalPlayer.videoWidth && modalPlayer.videoHeight) {
      modal.style.setProperty("--video-aspect", modalPlayer.videoWidth / modalPlayer.videoHeight);
    }
  });

  openButtons.forEach((button) => {
    if (!button.getAttribute("aria-label")) {
      button.setAttribute("aria-label", button.dataset.videoTitle || "打开演示视频");
    }

    button.addEventListener("click", () => {
      openVideo(button.dataset.videoSrc, button.dataset.videoTitle, button);
    });
  });

  document.querySelectorAll("[data-close-modal]").forEach((button) => {
    button.addEventListener("click", closeVideo);
  });

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && modal?.classList.contains("is-open")) {
      closeVideo();
    }
  });
}

function isVisible(element) {
  return Boolean(element && (element.offsetWidth || element.offsetHeight || element.getClientRects().length));
}

function syncCarouselVideo(video, shouldPlay) {
  if (!video) return;

  if (shouldPlay) {
    video.play().catch(() => {});
    return;
  }

  video.pause();
  video.currentTime = 0;
}

function buildVideoCarousel(carousel) {
  const base = carousel.dataset.videoBase;
  const count = Number(carousel.dataset.videoCount || 0);

  if (!base || !Number.isFinite(count) || count <= 0) {
    return;
  }

  const viewport = document.createElement("div");
  viewport.className = "video-carousel-viewport";

  const track = document.createElement("div");
  track.className = "video-carousel-track";

  const slides = [];

  for (let index = 1; index <= count; index += 1) {
    const slide = document.createElement("figure");
    slide.className = "video-slide";

    const video = document.createElement("video");
    video.muted = true;
    video.loop = true;
    video.playsInline = true;
    video.preload = "metadata";

    const source = document.createElement("source");
    source.src = `${base}/${index}.mp4`;
    source.type = "video/mp4";

    video.appendChild(source);
    slide.appendChild(video);
    track.appendChild(slide);
    slides.push(slide);
  }

  viewport.appendChild(track);

  const controls = document.createElement("div");
  controls.className = "video-carousel-controls";

  const prev = document.createElement("button");
  prev.className = "video-carousel-arrow";
  prev.type = "button";
  prev.setAttribute("aria-label", "上一个 Pair Data 视频");
  prev.innerHTML = "<span>&larr;</span>";

  const status = document.createElement("div");
  status.className = "video-carousel-status";

  const next = document.createElement("button");
  next.className = "video-carousel-arrow";
  next.type = "button";
  next.setAttribute("aria-label", "下一个 Pair Data 视频");
  next.innerHTML = "<span>&rarr;</span>";

  controls.append(prev, status, next);
  carousel.append(viewport, controls);

  let currentIndex = 0;

  const applyAspectRatio = (video) => {
    if (!video || !video.videoWidth || !video.videoHeight) return;
    viewport.style.setProperty("--carousel-aspect", `${video.videoWidth} / ${video.videoHeight}`);
  };

  const refreshPlayback = () => {
    slides.forEach((slide, slideIndex) => {
      const video = slide.querySelector("video");
      const isCurrent = slideIndex === currentIndex && isVisible(carousel);

      if (isCurrent) {
        applyAspectRatio(video);
      }

      syncCarouselVideo(video, isCurrent);
    });
  };

  const setIndex = (nextIndex) => {
    if (!slides.length) return;

    if (nextIndex < 0) {
      currentIndex = slides.length - 1;
    } else if (nextIndex >= slides.length) {
      currentIndex = 0;
    } else {
      currentIndex = nextIndex;
    }

    track.style.transform = `translateX(-${currentIndex * 100}%)`;
    status.textContent = `${currentIndex + 1} / ${slides.length}`;
    refreshPlayback();
  };

  carousel.__setIndex = setIndex;
  carousel.__getIndex = () => currentIndex;
  carousel.__refresh = refreshPlayback;

  prev.addEventListener("click", () => {
    activeCarousel = carousel;
    setIndex(currentIndex - 1);
  });

  next.addEventListener("click", () => {
    activeCarousel = carousel;
    setIndex(currentIndex + 1);
  });

  ["mouseenter", "focusin", "click"].forEach((eventName) => {
    carousel.addEventListener(eventName, () => {
      activeCarousel = carousel;
    });
  });

  slides.forEach((slide) => {
    const video = slide.querySelector("video");
    if (!video) return;

    video.addEventListener("loadedmetadata", () => {
      if (slide === slides[currentIndex]) {
        applyAspectRatio(video);
      }
    });
  });

  setIndex(0);
}

function wireCarouselKeyboard() {
  if (!videoCarousels.length) return;

  document.addEventListener("keydown", (event) => {
    if (modal?.classList.contains("is-open")) return;
    if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;

    const target = event.target;
    if (
      target instanceof HTMLElement &&
      (target.isContentEditable ||
        target.tagName === "INPUT" ||
        target.tagName === "TEXTAREA" ||
        target.tagName === "SELECT")
    ) {
      return;
    }

    const carousel =
      (activeCarousel && isVisible(activeCarousel) && activeCarousel) ||
      videoCarousels.find((candidate) => isVisible(candidate));

    if (!carousel || typeof carousel.__setIndex !== "function") return;

    event.preventDefault();
    const delta = event.key === "ArrowLeft" ? -1 : 1;
    carousel.__setIndex(carousel.__getIndex() + delta);
    carousel.focus();
  });
}

function initVideoCarousels() {
  videoCarousels.forEach((carousel, index) => {
    buildVideoCarousel(carousel);
    if (index === 0) {
      activeCarousel = carousel;
    }
  });

  wireCarouselKeyboard();
}

function initIclShowcase() {
  const showcase = document.querySelector("[data-icl-carousel]");
  const player = showcase?.querySelector("#icl-player");
  const thumbnails = Array.from(showcase?.querySelectorAll(".icl-thumbnail") || []);
  if (!player || !thumbnails.length) return;

  const previous = showcase.querySelector("[data-icl-prev]");
  const next = showcase.querySelector("[data-icl-next]");
  const position = showcase.querySelector("#icl-position");
  const thumbnailGroup = showcase.querySelector(".icl-thumbnails");
  let currentIndex = 0;
  let inViewport = false;
  let wantsPlayback = true;
  let language = "zh";

  // Start playback when the showcase enters view, while preserving native pauses.
  player.autoplay = false;
  player.loop = false;
  player.pause();

  const canPlay = () => inViewport && !document.hidden && !modal?.classList.contains("is-open");
  const number = (index) => String(index + 1).padStart(2, "0");

  const pauseAutomatically = () => {
    if (!player.paused) player.pause();
  };

  const updateLanguage = (lang) => {
    language = lang;
    const english = lang === "en";
    previous?.setAttribute("aria-label", english ? "Previous ICL video" : "上一个 ICL 视频");
    next?.setAttribute("aria-label", english ? "Next ICL video" : "下一个 ICL 视频");
    thumbnailGroup?.setAttribute("aria-label", english ? "Choose an ICL demonstration" : "选择 ICL 演示视频");
    player.setAttribute("aria-label", english
      ? `ICL demonstration ${number(currentIndex)} of ${thumbnails.length}`
      : `ICL 演示 ${number(currentIndex)}，共 ${thumbnails.length} 个视频`);
    thumbnails.forEach((thumbnail, index) => {
      thumbnail.setAttribute("aria-label", english ? `Play Demo ${number(index)}` : `播放演示 ${number(index)}`);
    });
  };

  const updateSelection = () => {
    thumbnails.forEach((thumbnail, index) => {
      const selected = index === currentIndex;
      thumbnail.classList.toggle("is-active", selected);
      thumbnail.setAttribute("aria-pressed", String(selected));
      thumbnail.style.setProperty("--icl-progress", "0");
    });
    if (position) position.textContent = `${number(currentIndex)} / ${String(thumbnails.length).padStart(2, "0")}`;
    updateLanguage(language);
  };

  const refreshPlayback = () => {
    if (!canPlay()) {
      pauseAutomatically();
    } else if (wantsPlayback) {
      if (player.ended) selectVideo(currentIndex + 1);
      else player.play().catch(() => {});
    }
  };

  const selectVideo = (index) => {
    const selected = (index + thumbnails.length) % thumbnails.length;
    if (selected === currentIndex) return;

    pauseAutomatically();
    currentIndex = selected;
    wantsPlayback = true;
    const thumbnail = thumbnails[currentIndex];
    player.poster = thumbnail.dataset.iclPoster;
    player.src = thumbnail.dataset.iclSrc;
    player.load();
    updateSelection();
    refreshPlayback();
  };

  thumbnails.forEach((thumbnail, index) => {
    thumbnail.addEventListener("click", () => selectVideo(index));
  });
  previous?.addEventListener("click", () => selectVideo(currentIndex - 1));
  next?.addEventListener("click", () => selectVideo(currentIndex + 1));

  showcase.addEventListener("keydown", (event) => {
    if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return;
    if (!(event.target instanceof Element)) return;
    const control = event.target.closest(".icl-thumbnail, [data-icl-prev], [data-icl-next]");
    if (!control || !showcase.contains(control)) return;

    event.preventDefault();
    selectVideo(currentIndex + (event.key === "ArrowLeft" ? -1 : 1));
    if (control.matches(".icl-thumbnail")) thumbnails[currentIndex].focus({ preventScroll: true });
  });

  player.addEventListener("play", () => {
    if (!canPlay()) pauseAutomatically();
    else wantsPlayback = true;
  });
  player.addEventListener("pause", () => {
    // Loading another source can discard queued pause events. Read the current
    // playback state instead of counting events from earlier sources.
    if (player.paused && canPlay() && !player.ended) wantsPlayback = false;
  });
  player.addEventListener("timeupdate", () => {
    const progress = Number.isFinite(player.duration) && player.duration > 0
      ? Math.min(1, player.currentTime / player.duration)
      : 0;
    thumbnails[currentIndex].style.setProperty("--icl-progress", String(progress));
  });
  player.addEventListener("ended", () => {
    wantsPlayback = true;
    if (canPlay()) selectVideo(currentIndex + 1);
  });

  const observer = new IntersectionObserver(([entry]) => {
    inViewport = entry.isIntersecting;
    refreshPlayback();
  });
  observer.observe(player);
  document.addEventListener("visibilitychange", refreshPlayback);

  updateSelection();
  iclShowcase = { player, refreshPlayback, updateLanguage };
}

function setLanguage(lang) {
  translatedElements.forEach(({ element, zh, en }) => {
    element.textContent = lang === "en" ? en : zh;
  });

  document.documentElement.lang = lang === "en" ? "en" : "zh-CN";
  document.querySelector(".architecture-embed").alt = lang === "en"
    ? englishCopy["diagram-caption"]
    : translatedElements.find(({ element }) => element.dataset.i18n === "diagram-caption").zh;
  document.querySelectorAll(".js-open-video").forEach((button) => {
    const title = lang === "en"
      ? button.dataset.videoTitleEn || "Demo video"
      : button.dataset.videoTitleZh || "已有演示";
    button.dataset.videoTitle = title;
    button.setAttribute("aria-label", lang === "en" ? `Open video: ${title}` : `放大查看：${title}`);
  });
  const closeButton = document.querySelector(".video-modal-close");
  closeButton.textContent = lang === "en" ? "Close" : "关闭";
  closeButton.setAttribute("aria-label", lang === "en" ? "Close video" : "关闭视频");
  if (!modal?.classList.contains("is-open")) {
    modalTitle.textContent = lang === "en" ? "Demo video" : "演示视频";
  }

  langButtons.forEach((button) => {
    button.classList.toggle("is-active", button.dataset.targetLang === lang);
    button.setAttribute(
      "aria-pressed",
      button.dataset.targetLang === lang ? "true" : "false"
    );
  });

  window.localStorage.setItem("website_pair_data_lang", lang);
  iclShowcase?.updateLanguage(lang);

  videoCarousels.forEach((carousel) => {
    if (typeof carousel.__refresh === "function") {
      carousel.__refresh();
    }
  });
}

function wireLanguageToggle() {
  if (!langButtons.length) return;

  const storedLang = window.localStorage.getItem("website_pair_data_lang");
  const initialLang = storedLang === "en" ? "en" : "zh";
  setLanguage(initialLang);

  langButtons.forEach((button) => {
    button.addEventListener("click", () => {
      setLanguage(button.dataset.targetLang);
    });
  });
}

buildToc();
updateActiveToc();
initVideoCarousels();
initIclShowcase();
wireVideos();
wireLanguageToggle();

window.addEventListener("scroll", updateActiveToc, { passive: true });
window.addEventListener("resize", () => {
  videoCarousels.forEach((carousel) => {
    if (typeof carousel.__refresh === "function") {
      carousel.__refresh();
    }
  });
});
